export const REGISTER_USER = "REGISTER_USER";
export const LOGIN_USER = "LOGIN_USER";
export const LOAD_USER = "LOAD_USER";
export const FAIL_USER = "FAIL_USER";
export const LOGOUT_USER = "LOGOUT_USER"
export const CURRENT_USER = "CURRENT_USER";
export const UPDATE_USERPASSWORD = "UPDATE_USERPASSWORD"
export const EDIT_USERPASSWORD = "EDIT_USERPASSWORD";

export const CLEAR_SUCCESSUSER ="CLEAR_SUCCESSUSER";

export const CLEAR_ERRORSUSER = "CLEAR_ERRORSUSER";